### Numpy Assignment

## Q1)Write a function so that the columns of the output matrix are powers of the input vector.</br>  The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])
n=5

In [3]:
# Using np.vander function
matrix1 = np.vander(x,n,increasing=False)
print(matrix1)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [4]:
# similat matrix can be obtained in this way.
matrix2 = np.column_stack([x**(n-i-1) for i in range(n)])
print(matrix2)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


### Q2)Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [81]:
def moving_avg(newlist,n):
    csum, moving_avgvalues = [0],[]
    for i,x in enumerate(newlist,1):
        csum.append(csum[i-1] + x) # doing cumulative sum of the elements.
        if i>=n: # when n comes to window number we are subracting the cummulative sum of the elements with window 3.
            moving_avgs = round(((csum[i]-csum[i-n])/n),2)
            moving_avgvalues.append(moving_avgs)
    print('cumulative sum',csum)
    print("Moving avg values: ",moving_avgvalues)

In [82]:
newlist = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
n=3

moving_avg(newlist,n)

cumulative sum [0, 3, 8, 15, 17, 25, 35, 46, 111, 183, 264, 363, 463, 613]
Moving avg values:  [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
